name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, macOS]

    steps:
    - uses: actions/checkout@v3

    - name: Compile and package
      run: make
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyFramework.xcframework
        path: _install

    - name: Cleanup
      run: make clean
