name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, macOS]

    steps:
    - uses: actions/checkout@v3

    - name: Compile and package
      run: make
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyFramework.xcframework
        path: _install

    - name: Create Release
      id: create_release
      uses: actions/create-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./_install/MyFramework.xcframework
        asset_name: MyFramework.xcframework
        asset_content_type: application/zip

    - name: Cleanup
      run: make clean
